swagger: '2.0'
info:
  description: >-
    The TurnOnline.biz REST API designed for cooperation with on-premise
    accounting system.
  version: 1.0-SNAPSHOT
  title: TurnOnline.biz On-premise Accounting API
  contact:
    name: TurnOnline.biz Team
    url: 'https://www.turnonline.biz'
    email: support@turnonline.biz
  license:
    name: LGPL-2.1
    url: >-
      https://github.com/turnonline/on-premise-accounting-api/blob/master/LICENSE
host: onpremise.swagger.io
basePath: /onpremise
tags:
  - name: Address book
    description: The on-premise accounting address book.
  - name: Number series
    description: The on-premise accounting number series management.
schemes:
  - http
security:
  - Basic: []
paths:
  /addressBook:
    post:
      tags:
        - Address book
      summary: Creates a new contact
      description: Creates a new contact in the address book. Duplicates are allowed.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/ContactCard'
      responses:
        '201':
          description: Contact response
          schema:
            $ref: '#/definitions/ContactCard'
        '400':
          description: >-
            The error indicates that client has made a request that server
            couldn't understand. The client should not repeat the request
            without modifications.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: The error when the authentication credential fails.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
  '/addressBook/{id}':
    get:
      tags:
        - Address book
      summary: Returns the contact
      description: Returns a single contact based on the supplied ID.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contact to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Contact response.
          schema:
            $ref: '#/definitions/ContactCard'
        '401':
          description: The error when the authentication credential fails.
        '404':
          description: >-
            The error when client tries to retrieve a resource that doesn't
            exist.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
    put:
      tags:
        - Address book
      summary: Updates the contact
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of contact to fetch
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/ContactCard'
      responses:
        '201':
          description: Contact response
          schema:
            $ref: '#/definitions/ContactCard'
        '400':
          description: >-
            The error indicates that client has made a request that server
            couldn't understand. The client should not repeat the request
            without modifications.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: The error when the authentication credential fails.
        '404':
          description: The error when client tries to update a resource that doesn't exist.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
    delete:
      tags:
        - Address book
      summary: Deletes the contact
      description: Deletes a single contact based on the supplied ID.
      parameters:
        - name: id
          in: path
          description: ID of contact to fetch
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Contact deleted
        '401':
          description: The error when the authentication credential fails.
        '404':
          description: The error when client tries to delete a resource that doesn't exist.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
  /numberSeries:
    post:
      tags:
        - Number series
      summary: Creates a new number series
      description: Creates a new number series in on-premise accounting system.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/NumberSeries'
      responses:
        '201':
          description: Number series response
          schema:
            $ref: '#/definitions/NumberSeries'
        '400':
          description: >-
            The error indicates that client has made a request that server
            couldn't understand. The client should not repeat the request
            without modifications.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: The error when the authentication credential fails.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
  '/numberSeries/{id}':
    put:
      tags:
        - Number series
      summary: Updates the number series
      description: Updates the number series in on-premise accounting system.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of number series to fetch
          required: true
          type: integer
          format: int32
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/NumberSeries'
      responses:
        '201':
          description: Number series response
          schema:
            $ref: '#/definitions/NumberSeries'
        '400':
          description: >-
            The error indicates that client has made a request that server
            couldn't understand. The client should not repeat the request
            without modifications.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: The error when the authentication credential fails.
        '404':
          description: The error when client tries to update a resource that doesn't exist.
        '408':
          description: >-
            The server timed out processing of the request. The client may
            repeat the request without modifications at any later time.
        '500':
          description: >-
            It's a failure of the server. The client can repeat the request
            without modifications at any later time.
securityDefinitions:
  Basic:
    type: basic
definitions:
  Account:
    type: object
  BankAccount:
    type: object
  BillingUnit:
    type: object
  ContactCard:
    type: object
    required:
      - company
      - postalAddressSame
      - vatPayer
    properties:
      businessName:
        type: string
        description: Company business name.
      city:
        type: string
        description: City.
      company:
        type: boolean
        description: The boolean indication whether contact represents a business entity.
        default: false
      companyId:
        type: string
        description: Company ID.
      contactEmail:
        type: string
        description: Email as a contact email address.
      id:
        type: string
        description: The contact card identification.
      name:
        type: string
        description: Personal name.
      postalAddressBusinessName:
        type: string
        description: Company postal address business name.
      postalAddressCity:
        type: string
        description: Postal address city.
      postalAddressName:
        type: string
        description: Personal postal address name.
      postalAddressSame:
        type: boolean
        description: >-
          The boolean indication whether contact postal address is same as
          company/personal address. If not postal address is being expected.
        default: false
      postalAddressState:
        type: string
        description: Postal address country code.
      postalAddressStreet:
        type: string
        description: Postal address street and street number.
      postalAddressSurname:
        type: string
        description: Personal postal address surname.
      postalAddressZip:
        type: string
        description: Postal address code.
      state:
        type: string
        description: Country code.
      street:
        type: string
        description: Street and street number.
      surname:
        type: string
        description: Personal surname.
      taxId:
        type: string
        description: Company tax ID.
      vatId:
        type: string
        description: Company VAT ID. Provided if vatPayer property is true.
      vatPayer:
        type: boolean
        description: The boolean indication whether contact business entity is VAT payer.
        default: false
      zip:
        type: string
        description: Postal code.
    description: Address book card that represents business partner contact.
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  IncomingInvoice:
    type: object
  Invoice:
    type: object
  NumberSeries:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: The number series identification.
      name:
        type: string
        description: The name of the number series.
      periods:
        type: array
        items:
          $ref: '#/definitions/Period'
    description: >-
      The accounting number series as a definition of the invoice number
      increment.
  Payment:
    type: object
  Period:
    type: object
    required:
      - code
    properties:
      code:
        type: string
        description: >-
          The accounting period's code, generally as a year. For example 4
          digits '2016'.
      current:
        type: string
        description: The current value of the increment.
      numberOfChars:
        type: integer
        format: int32
        description: The max number of characters or digits.
      postfix:
        type: string
        description: >-
          The number series postfix. Possible format either as static text or
          dynamic: for example %YY%.
      prefix:
        type: string
        description: >-
          The number series prefix. Possible format either as static text or
          dynamic: for example %YY%.
    description: Accounting period
  Product:
    type: object
